set(OPENGL_VERSION "1.1") # Force a low OpenGL version
set(CUSTOMIZE_BUILD ON CACHE BOOL "" FORCE) # Customize raylib build
# Disable not required features
set(USE_AUDIO OFF CACHE BOOL "" FORCE)
set(SUPPORT_CAMERA_SYSTEM OFF CACHE BOOL "" FORCE)
set(SUPPORT_SCREEN_CAPTURE OFF CACHE BOOL "" FORCE)
set(SUPPORT_GIF_RECORDING OFF CACHE BOOL "" FORCE)
set(SUPPORT_GESTURES_SYSTEM OFF CACHE BOOL "" FORCE)
set(SUPPORT_MOUSE_GESTURES OFF CACHE BOOL "" FORCE)
set(SUPPORT_VR_SIMULATOR OFF CACHE BOOL "" FORCE)
set(SUPPORT_DISTORTION_SHADER OFF CACHE BOOL "" FORCE)
# Enable additional image options
set(SUPPORT_FILEFORMAT_BMP ON CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_TGA ON CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_JPG ON CACHE BOOL "" FORCE)